### ISSUE TITLE
No devices

### ISSUE THREAD

**Issue by abko** [flochtililoch/lirc-state-api#7]
@flochtililoch 
Hello, I am interested in using lirc-state-api. I installed it on my raspberry pi and am planning to hook it up with the homebridge-lirc-accessory plugin. 

Using my own config, but also the example config file it looks like no devices are recognised. When accessing http://raspberrypi.local:3001/devices I get an empty array as response:
`[]`

Can you advise what I might be doing wrong?

This is what my config looks like.

```
[
  {
    "id": "stb",
    "lirc_id": "stb",
    "name": "stb",
    "states": [
      {
        "id": "power",
        "type": "loop",
        "values": [false, true],
        "keys": {
          "next": "KEY_POWER"
        }
      }
    ]
  }
]
```

**Comment by flochtililoch** [comment]
can you detail your installation path, as well as the command you're running to start the app?

**Comment by abko** [comment]
Thanks for your prompt reply!

I installed it using `sudo npm install -g homebridge-lirc-accessory`, I used the following command: `lirc-state-api -c=/var/lib/homebridge/lircstate.conf`. It finds lira-state-api here `/usr/local/bin/lirc-state-api`.

After running it shows `listening on port 3001`

**Comment by flochtililoch** [comment]
I think the issue might be because your config isn't a `json` file. Rename `lircstate.conf` to `lircstate.json` and change your start command accordingly, let me know if that helps

**Comment by abko** [comment]
Thanks. I believe that did the trick. I need to do some digging on my config file, since I am getting another error now. First dinner time :-)
`TypeError: Cannot read property 'forEach' of undefined
    at new States (/usr/local/lib/node_modules/lirc-state-api/lib/model/states.js:17:24)
    at Device.get states [as states] (/usr/local/lib/node_modules/lirc-state-api/lib/model/device.js:27:22)
    at Device.serialize (/usr/local/lib/node_modules/lirc-state-api/lib/model/device.js:82:24)
    at devices.map (/usr/local/lib/node_modules/lirc-state-api/lib/model/devices.js:22:48)
    at Array.map (native)
    at Devices.serialize (/usr/local/lib/node_modules/lirc-state-api/lib/model/devices.js:22:25)
    at app.get (/usr/local/lib/node_modules/lirc-state-api/lib/api/http.js:5:27)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/lirc-state-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/lirc-state-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/lirc-state-api/node_modules/express/lib/router/route.js:112:3)`

**Comment by flochtililoch** [comment]
you'll likely need to set the key `"dependencies"` in your config file (empty `[]` should be enough)

**Comment by abko** [comment]
Thanks, that solved the first part!

I am making progress, but bumping into another issue. I have the impression the link between lirc-state-api and lirc is not correctly established.

I get the following error message when pressing a button on the device remote control from lirc-state-api
```
(node:847) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: value [object Object] does not exist in this state.
(node:847) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also the message is only shown after I first set a state (using homebridge-lirc-accessory), before that no logging is shown, nor the state is updated.

Additionally state changes triggered through homebridge-lirc-accessory don't send out the remote command to the device from the raspberry pi (but the state is changed). 
Manually lirc works as expected (e.g. using irw to check what's being received, using irsend to issue the remote command).

I guess I am close. Any hint what I am doing wrong would be appreciated. 

Thanks for all help!

**Comment by flochtililoch** [comment]
Could you paste again your updated configuration here? I have the feeling there might be some error there but that may as well be something else

**Comment by abko** [comment]
The latest version is below. I initially tried it with empty brackets []. In the current version I added another button in an attempt to see if having an actual dependency solved the problem. This had no effect.

```
[
  {
    "id": "amino",
    "lirc_id": "amino",
    "name": "Amino",
    "send_delay": 500,
    "receive_delay": 100,
    "states": [
      {
        "id": "power",
        "type": "loop",
        "values": [false, true],
        "keys": {
          "next": "KEY_POWER"
        }
      },
      {
        "id": "guide",
        "type": "loop",
        "values": [false, true],
        "keys": {
          "next": "KEY_EPG"
        }
      }
    ],
    "dependencies": [{
        "states": ["guide"],
        "depends": [
          {
            "id": "power",
            "values": [true]
          }
        ]
      }]
  }
]

```

**Comment by flochtililoch** [comment]
I think the log lines you're seeing can be ignored (I should fix these at some point).
Since you can see the state changing, this should also trigger the LIRC commands.
You can run the app in debug mode:

```sh
DEBUG=* lirc-state-api -c=/path/to/config.json
```
and should see more logs, in particular something like:

```
will send KEY_FOO to device
```

key/device should match the request made from homebridge. If you see this, I suspect something off with your LIRC configuration but to be honest I haven't play with it in a while, and can't remember anything special with this issue. Have you try setting up [lirc-web](https://github.com/alexbain/lirc_web)? This uses the same library [lirc_node](https://github.com/alexbain/lirc_web) as this project, so that would be a good indicator as whether the problem comes from the lirc_node lib or is an actual bug from lirc-state-api

**Comment by abko** [comment]
When I try to control the stb from the Home app I get the following;
```
  lirc-state-api#state State power setting to false. +5s
  lirc-state-api#state State power onafter callback. +4ms
  lirc-state-api#state State power set to expected value: false +3ms
  express:router dispatching GET /devices/amino/states/power +3s
  express:router query  : /devices/amino/states/power +3ms
  express:router expressInit  : /devices/amino/states/power +13ms
  express:router jsonParser  : /devices/amino/states/power +4ms
  body-parser:json skip empty body +3s
```

When I use the original remote I get:
```
  lirc-state-api#device received KEY_POWER for amino, updating state +4s
  lirc-state-api#utils/assert false is not valid, sending error with message +1ms
(node:7639) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: value [object Object] does not exist in this state.
```

I just setup lirc-web. It is working as expected.

**Comment by abko** [comment]
I did some more experiments. It seems it does respond after initially starting lirc-state-api. This is the responds I get when using the Home app initially:
```
  express:router dispatching PUT /devices/amino/states/power +5s
  express:router query  : /devices/amino/states/power +4ms
  express:router expressInit  : /devices/amino/states/power +4ms
  express:router jsonParser  : /devices/amino/states/power +3ms
  body-parser:json content-type "application/json" +5s
  body-parser:json content-encoding "identity" +4ms
  body-parser:json read body +2ms
  body-parser:json parse body +4ms
  body-parser:json parse json +2ms
  lirc-state-api#state State power setting to true. +4s
  lirc-state-api#state State power leaving: false for true +2ms
  lirc-state-api#device will send KEY_POWER to amino +2ms
  lirc-state-api#state State power onafter callback. +559ms
  lirc-state-api#state State power set to expected value: true +2ms
```

As soon as I use the I original remote I get the message in the previous post:
```
  lirc-state-api#device received KEY_POWER for amino, updating state +9s
  lirc-state-api#utils/assert false is not valid, sending error with message +16ms
(node:7884) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: value [object Object] does not exist in this state.
(node:7884) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

 From that moment onwards use of the Home app to power on the stb results in:
```
  lirc-state-api#state State power setting to false. +5s
  lirc-state-api#state State power onafter callback. +4ms
  lirc-state-api#state State power set to expected value: false +3ms
  express:router dispatching GET /devices/amino/states/power +3s
  express:router query  : /devices/amino/states/power +3ms
  express:router expressInit  : /devices/amino/states/power +13ms
  express:router jsonParser  : /devices/amino/states/power +4ms
  body-parser:json skip empty body +3s
```

**Comment by abko** [comment]
@flochtililoch Do you have any hints of what potential issues I can investigate further to get my setup working?

**Comment by flochtililoch** [comment]
Apologies for the delayed reply. I was able to reproduce the issues you're facing. Looking back at the code, it seems like I never completed the implementation around the feature that updates the state when receiving IR signals. Unfortunately I have little time these days to work on this project so I won't be able to address the issue anytime soon. I'll keep this issue open though so I can work on it when I have more time on hands, in the mean time feel free to open a pull request!

**Comment by abko** [comment]
Hi @flochtililoch, thanks for your reply. No worries about the delay, I am glad you confirmed the problem. I'll look into the pull request. Would be nice if you find some time somewhere in future :-)

**Comment by flochtililoch** [comment]
@abko [v0.0.3](https://github.com/flochtililoch/lirc-state-api/releases/tag/v0.0.3) should solve the issues you were facing. Thanks for reporting it!

**Comment by abko** [comment]
Thank you! I am away from my home until the weekend, but will try as soon as I am home!

Thanks a lot. Kind regards.

**Comment by abko** [comment]
@flochtililoch I did some testing and indeed IR commands are now being picked up and updating the state correctly. Great. Thanks. I noticed however that the state in the Home app does not get updated until I kill the Home app and restart it. Could it be that there is some state update function that needs to be called when the state is changed via a receive IR command?

**Comment by flochtililoch** [comment]
Glad it’s working for you now. Yes we would need to send a request to he homebridge instance to refresh its state. I’ll see if I can get something working when I have a moment!

**Comment by abko** [comment]
Thanks! Let me know if I can be of any help with testing!
