### ISSUE TITLE
First launch

### ISSUE THREAD

**Issue by mazafra1** [flochtililoch/lirc-state-api#9]
Probably this is not an issue but a documentation request.

How is this suppose to be installed or compile, or run. Not a lot of information in README.

**Run**
$ lirc-state-api -c=/path/to/config.json [-p=1234]
lirc-state-api: command not found

Besides, is this suppose to run together with your lirc_web or is is this standalone?

Thanks.

**Comment by flochtililoch** [comment]
Long overdue reply, sorry about that! 

> Probably this is not an issue but a documentation request.
> 
> How is this suppose to be installed or compile, or run. Not a lot of information in README.
> 
> **Run**
> $ lirc-state-api -c=/path/to/config.json [-p=1234]
> lirc-state-api: command not found
> 

This could be made more clear in the doc, this assumes your `$PATH` includes `node_modules/.bin`. If not, use the following:

```shell
$ node_modules/.bin/lirc-state-api -c=/path/to/config.json [-p=1234]
```

> Besides, is this suppose to run together with your lirc_web or is is this standalone?

This does not require lirc_web, but you need the LIRC daemon running for this to work.
